<?php

/**
 * Copyright 2025 oliv (http://opoink.com/)
 * Licensed under MIT, see LICENSE.md
 */

namespace Opoink\Oliv\Lib\Plugin;

use JsonException;
use Opoink\Oliv\Lib\Writer as FileWriter;

class Layout
{
    private const GENERATED = '<!-- Generated by OLIV Layout; edit plugin resources/layout files. -->';

    public function createLayoutByPageName(?string $pageName): void
    {
        if ($pageName === null || $pageName === '') {
            return;
        }
        if (! preg_match('/^[a-zA-Z0-9_][a-zA-Z0-9_.-]*$/D', $pageName)) {
            $this->warning('Invalid layout page name.', ['page' => $pageName]);

            return;
        }

        $fileName = str_replace(' ', '', ucwords(str_replace('.', ' ', $pageName)));
        $this->createPageComponent($pageName, $this->targetDirectory(), $fileName, 'vue');
    }

    public function createPageComponent(string $pageName, string $targetDir, string $fileName, string $ext): void
    {
        $layouts = [];
        $hasSource = false;
        foreach ($this->pluginDirectories() as $directory) {
            $file = $directory.DS.'resources'.DS.'layout'.DS.$pageName.'.json';
            if (! is_file($file)) {
                continue;
            }

            $hasSource = true;
            try {
                $data = json_decode(file_get_contents($file), true, 512, JSON_THROW_ON_ERROR);
                if (! is_array($data)) {
                    $this->warning('Layout must contain an array or keyed object.', ['file' => $file]);

                    continue;
                }
                $layouts[] = $data;
            } catch (JsonException $exception) {
                $this->warning('Invalid layout JSON.', ['file' => $file, 'error' => $exception->getMessage()]);
            }
        }

        $target = $targetDir.DS.$fileName.'.'.$ext;
        if ($layouts === []) {
            if (! $hasSource) {
                $this->removeGeneratedFile($target);
            }

            return;
        }

        $content = self::GENERATED."\n".$this->toVueComponent($this->mergeLayouts(...$layouts));
        if (is_file($target) && file_get_contents($target) === $content) {
            return;
        }

        $writer = new FileWriter;
        $writer->setDirPath($targetDir);
        $writer->setData($content);
        $writer->setFilename($fileName);
        $writer->setFileextension($ext);
        $writer->write();
    }

    /**
     * Generate all declared pages before Vite evaluates its page import glob.
     */
    public function compileLayouts(): void
    {
        $pages = [];
        foreach ($this->pluginDirectories() as $directory) {
            foreach (glob($directory.DS.'resources'.DS.'layout'.DS.'*.json') ?: [] as $file) {
                $pages[pathinfo($file, PATHINFO_FILENAME)] = true;
            }
        }

        $targets = [];
        foreach (array_keys($pages) as $page) {
            $this->createLayoutByPageName($page);
            $targets[str_replace(' ', '', ucwords(str_replace('.', ' ', $page))).'.vue'] = true;
        }

        foreach (glob($this->targetDirectory().DS.'*.vue') ?: [] as $file) {
            if (! isset($targets[basename($file)])) {
                $this->removeGeneratedFile($file);
            }
        }
    }

    protected function targetDirectory(): string
    {
        
        return getPath('storage/framework/vue/pages');
    }

    protected function pluginDirectories(): array
    {
        $plugins = getPluginsConfig()->getData('plugins', []);
        if (! is_array($plugins)) {
            $this->warning('Plugin configuration must contain a plugins array.');

            return [];
        }

        $directories = [];
        foreach ($plugins as $plugin) {
            if (! is_string($plugin) || ! preg_match('/^[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)+$/D', $plugin)) {
                $this->warning('Invalid plugin name in layout configuration.');

                continue;
            }
            $directories[] = getPluginDir($plugin);
        }

        return array_values(array_unique($directories));
    }

    private function removeGeneratedFile(string $file): void
    {
        if (is_file($file) && str_starts_with(file_get_contents($file), self::GENERATED)) {
            unlink($file);
        }
    }

    /**
     * Names identify nodes across one page. First component/parent wins;
     * attributes use later values and children retain first-contribution order.
     *
     * @param  array<array-key, mixed>  ...$layouts  Plugin definitions in configured order.
     * @return list<array{name: string, component: string, export: string, attr: array, children: array}>
     */
    public function mergeLayouts(array ...$layouts): array
    {
        $nodes = [];
        $parents = [];
        $roots = [];
        foreach ($layouts as $layout) {
            $this->collectNodes($layout, null, $nodes, $parents, $roots);
        }

        $result = [];
        foreach (array_keys($roots) as $name) {
            if (! isset($parents[$name])) {
                $node = $this->buildNode((string) $name, $nodes);
                if ($node !== null) {
                    $result[] = $node;
                }
            }
        }

        return $result;
    }

    private function collectNodes(array $layout, ?string $parent, array &$nodes, array &$parents, array &$roots): void
    {
        foreach ($layout as $key => $data) {
            if (! is_array($data)) {
                $this->warning('Layout node must be an array.');

                continue;
            }

            $name = $data['name'] ?? (is_string($key) ? $key : null);
            if (! is_string($name) || trim($name) === '') {
                $this->warning('Layout node is missing a name.');

                continue;
            }

            if ($parent !== null) {
                if (isset($parents[$name]) && $parents[$name] !== $parent) {
                    $this->warning('Layout node has conflicting parents; keeping the first.', ['node' => $name]);

                    continue;
                }

                $ancestor = $parent;
                while ($ancestor !== null && $ancestor !== $name) {
                    $ancestor = $parents[$ancestor] ?? null;
                }
                if ($ancestor === $name) {
                    $this->warning('Cyclic layout reference skipped.', ['node' => $name]);

                    continue;
                }

                $parents[$name] = $parent;
                $nodes[$parent]['children'][$name] = true;
            } else {
                $roots[$name] = true;
            }

            $nodes[$name] ??= ['name' => $name, 'attr' => [], 'children' => []];
            $component = $this->componentDefinition($data, $name);
            if ($component !== null) {
                if (isset($nodes[$name]['component']) && (
                    $nodes[$name]['component'] !== $component['component'] ||
                    $nodes[$name]['export'] !== $component['export']
                )) {
                    $this->warning('Conflicting layout component; keeping the first.', ['node' => $name]);
                } else {
                    $nodes[$name] = array_replace($nodes[$name], $component);
                }
            }

            if (array_key_exists('remove', $data)) {
                $nodes[$name]['remove'] = $data['remove'] === true;
            }
            if (isset($data['attr'])) {
                if (is_array($data['attr'])) {
                    $nodes[$name]['attr'] = array_replace($nodes[$name]['attr'], $data['attr']);
                } else {
                    $this->warning('Layout attributes must be an object.', ['node' => $name]);
                }
            }
            if (array_key_exists('children', $data)) {
                if (is_array($data['children'])) {
                    $this->collectNodes($data['children'], $name, $nodes, $parents, $roots);
                } else {
                    $this->warning('Layout children must be an array or keyed object.', ['node' => $name]);
                }
            }
        }
    }

    /**
     * Support existing default and single named imports, including Inertia Head.
     *
     * @return array{component: string, export: string}|null
     */
    private function componentDefinition(array $data, string $name): ?array
    {
        $path = $data['component'] ?? null;
        $export = 'default';
        if (! array_key_exists('component', $data) && isset($data['import'])) {
            if (! is_string($data['import']) || ! preg_match(
                '/^\s*import\s+(?:[a-zA-Z_$][\w$]*|\{\s*([a-zA-Z_$][\w$]*)(?:\s+as\s+[a-zA-Z_$][\w$]*)?\s*\})\s+from\s+([\'"])([^\'"\r\n]+)\2\s*;?\s*$/D',
                $data['import'],
                $matches
            )) {
                $this->warning('Unsupported layout import; use component or a single component import.', ['node' => $name]);

                return null;
            }
            $path = $matches[3];
            $export = ($matches[1] ?? '') !== '' ? $matches[1] : 'default';
        }

        if ($path === null && ! array_key_exists('component', $data)) {
            return null;
        }
        if (! is_string($path) || trim($path) === '' || preg_match('/[\x00-\x1f<>]/', $path)) {
            $this->warning('Layout component path must be a nonempty module path.', ['node' => $name]);

            return null;
        }

        $path = str_replace('\\', '/', $path);
        // if (str_starts_with($path, '@@Plugins@@/')) {
        //     $path = 'Plugins/'.substr($path, strlen('@@Plugins@@/'));
        // }


        return ['component' => $path, 'export' => $export];
    }

    private function buildNode(string $name, array $nodes): ?array
    {
        $node = $nodes[$name];
        if ($node['remove'] ?? false) {
            return null;
        }
        if (! isset($node['component'])) {
            $this->warning('Unresolved layout locator skipped with its subtree.', ['node' => $name]);

            return null;
        }

        $children = [];
        foreach (array_keys($node['children']) as $child) {
            $childNode = $this->buildNode((string) $child, $nodes);
            if ($childNode !== null) {
                $children[] = $childNode;
            }
        }
        unset($node['remove']);
        $node['children'] = $children;

        return $node;
    }

    public function toVueComponent(array $layout): string
    {
        $imports = [];
        $template = $this->renderNodes($layout, $imports, 1);

        return "<script setup>\n".implode('', $imports)."</script>\n<template>\n".$template."</template>\n";
    }

    private function renderNodes(array $layout, array &$imports, int $level): string
    {
        $content = '';
        foreach ($layout as $node) {
            $path = $node['component'];
            $export = $node['export'];
            $identifier = 'OlivComponent_'.substr(hash('sha256', $path.'#'.$export), 0, 16);
            $binding = $export === 'default' ? $identifier : '{ '.$export.' as '.$identifier.' }';
            $imports[$identifier] = 'import '.$binding.' from '.json_encode($path, JSON_UNESCAPED_SLASHES | JSON_HEX_TAG | JSON_THROW_ON_ERROR).";\n";

            $attributes = '';
            foreach ($node['attr'] as $key => $value) {
                if (! is_string($key) || ! preg_match('/^[^\s"\'<>\/=]+$/Du', $key) || (! is_scalar($value) && $value !== null)) {
                    $this->warning('Invalid layout attribute skipped.', ['node' => $node['name']]);

                    continue;
                }
                $attributes .= ' '.$key.'="'.htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8').'"';
            }

            $indent = str_repeat("\t", $level);
            if ($node['children'] === []) {
                $content .= $indent.'<'.$identifier.$attributes." />\n";
            } else {
                $content .= $indent.'<'.$identifier.$attributes.">\n";
                $content .= $this->renderNodes($node['children'], $imports, $level + 1);
                $content .= $indent.'</'.$identifier.">\n";
            }
        }

        return $content;
    }

    protected function warning(string $message, array $context = []): void
    {
        logger()->warning('OLIV Layout: '.$message, $context);
    }
}
