<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Reset Your Password</title>
		<style>
			body {
				font-family: Arial, sans-serif;
				background-color: #f4f4f4;
				margin: 0;
				padding: 0;
			}
			.email-container {
				max-width: 600px;
				margin: 20px auto;
				background: #ffffff;
				padding: 20px;
				border-radius: 8px;
				box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
			}
			.btn {
				display: inline-block;
				padding: 12px 20px;
				color: #ffffff !important;
				background: #ea872f;
				text-decoration: none;
				border-radius: 5px;
				font-size: 16px;
			}
			.code {
				font-size: 24px;
				font-weight: bold;
				margin: 15px 0;
				background: #f4f4f4;
				padding: 10px;
				display: inline-block;
			}
			.footer {
				margin-top: 20px;
				font-size: 12px;
				color: #666;
				text-align: center;
			}
		</style>
	</head>
	<body>
		<div class="email-container">
			<h2>Hello <?= $user->firstname ?> <?= $user->lastname ?></h2>

			<p>
				You recently requested to reset your password for <strong><?= config('oliv.vite_admin_app_name') ?></strong>. 
				<br />
				If this request was made by you, please follow the instructions below to proceed. 
				<br />
				Use the code below to proceed:
			</p>
			<div class="code"><?= $code ?></div>


			<p>Or click the button below to reset your password:</p>
			<p style="text-align: center;">
				<a href="<?= url('/' . getAdminUrl() . '/reset-password') ?>" class="btn">Reset Password</a>
			</p>
			<p class="footer">If you did not request this, please ignore this email.</p>
		</div>
	</body>
</html>
